server:
  port: 8888
  shutdown: graceful
spring:
  zipkin:
    base-url: http://zipkin:9411/
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://bitbucket.org/isc_project/config
          searchPaths: '{application}'
          username: bitbucketconfigisc
          password: ATBB8g3PjG6Ts9swUQc5S3D8HLTb76F8BD56
          refreshRate: 15
          default-label: master

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://isc:4RKsJQfuvvuG@localhost:8761/eureka/
  instance:
    metadata-map:
      "prometheus.scrape": "true"
      "prometheus.path": "/actuator/com.isc.master.prometheus"
      "prometheus.port": "8889"
      "sys.module": "core"

management:
  security:
    enabled: false
  server:
    port: 8889
  health:
    config:
      enabled: false
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,com.isc.master.prometheus
  metrics:
    export:
      prometheus:
        enabled: true

    #logging:
    #level:
    # root: DEBUG
